### ISSUE TITLE
[Bug] CLI error

### ISSUE THREAD

**Issue by CilooW** [storybookjs/addon-styling-webpack#7]
### Describe the bug

I want to change preset/scss in my projet , with this addon. I installed the storybook CLI. Then, I get an error when installing addon with the Storybook CLI

### Steps to reproduce the behavior

1. run the command `npx storybook@latest add @storybook/addon-styling-webpack`
2. see error "spawn npw ENOENT" ( spawnargs: ['@storybook/auto-config', 'styling' ] )

### Expected behavior

I should have the new addon installed

### Screenshots and/or logs

![image](https://github.com/storybookjs/addon-styling-webpack/assets/19734086/fb06b19c-39e4-4618-b916-c6d3554d0867)

### Environment

 - OS: Windows 11
 - Node.js version: v16.14.2
 - NPM version: 8.5.0
 - Browser (if applicable): chrome
 - Browser version (if applicable): V116.0

### Additional context

I look for a simple solution to uninstall preset/scss and have something else in my package to handle scss preprocessing, as I run into scss duplicating, especially for the global part... and I was hoping maybe this addon could help me resolve my problems :) .

**Comment by CilooW** [comment]
additionnal information, I tried this but not effective : 
![image](https://github.com/storybookjs/addon-styling-webpack/assets/19734086/b17c0ee8-23fb-4c0b-9c0e-696a9a90b652)
it just... terminate the task, like this

**Comment by ecoms-ye** [comment]
same error in macOS with pnpm:

```shell
  throw error;
  ^

Error: spawn pnpm dlx ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pnpm dlx',
  path: 'pnpm dlx',
  spawnargs: [ '@storybook/auto-config', 'styling' ]
}

Node.js v18.18.0
```

**Comment by maciej-jezierski** [comment]
Same here MacOS. Fresh installation of storybook

```pnpm dlx storybook@latest add @storybook/addon-styling-webpack
.../Library/pnpm/store/v3/tmp/dlx-30243  |  WARN  deprecated @babel/plugin-proposal-private-property-in-object@7.21.0-placeholder-for-preset-env.2
.../Library/pnpm/store/v3/tmp/dlx-30243  |  WARN  deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
.../Library/pnpm/store/v3/tmp/dlx-30243  |  WARN  deprecated @babel/plugin-proposal-class-properties@7.18.6
.../Library/pnpm/store/v3/tmp/dlx-30243  |  WARN  deprecated @babel/plugin-proposal-optional-chaining@7.21.0
.../Library/pnpm/store/v3/tmp/dlx-30243  | +617 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../Library/pnpm/store/v3/tmp/dlx-30243  | Progress: resolved 638, reused 617, downloaded 0, added 617, done
Verifying @storybook/addon-styling-webpack
Installing @storybook/addon-styling-webpack@^0.0.4
Adding '@storybook/addon-styling-webpack' to main.js addons field.
Running postinstall script for @storybook/addon-styling-webpack
/Users/maciej/Library/pnpm/store/v3/tmp/dlx-30243/node_modules/.pnpm/@storybook+cli@7.4.5/node_modules/@storybook/cli/bin/index.js:23
  throw error;
  ^

Error: spawn pnpm dlx ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pnpm dlx',
  path: 'pnpm dlx',
  spawnargs: [ '@storybook/auto-config', 'styling' ]
}

Node.js v18.14.0
 ERROR  Command failed with exit code 7: storybook add @storybook/addon-styling-webpack```

**Comment by maciej-jezierski** [comment]
My case is solved. I used Tailwind and seems this package is not supporting it. Moving to: [@storybook/addon-themes](https://github.com/storybookjs/storybook/tree/next/code/addons/themes) solved it.

Mistake comes from deprecated package description:
https://github.com/storybookjs/addon-styling

Error message could be more intuitive

**Comment by Integrayshaun** [comment]
Hey @CilooW I just published a fix that _should_ solve your problem on Windows. Can you give `0.0.5` a try?

**Comment by CilooW** [comment]
@Integrayshaun unfortunately, I installed manually the addon by copying the line in my package.json, because the install with cli didn't work (npm, says no target found, as if the package didn't exist). 
then when I call the auto-config, I have the same problem than above ^^"

**Comment by Integrayshaun** [comment]
Hey @CilooW I'm sorry that this is still a problem for you :( despite the error being the same, can you share the output with me? I just want to confirm that your machine isn't using an old cache from the previous npx attempts.

**Comment by CilooW** [comment]
I did a `npm cache clean --force` before writing this message of course :) 
here are my attemps with the auto-config : 
![image](https://github.com/storybookjs/addon-styling-webpack/assets/19734086/3e76eb00-abdd-4b87-b089-6cc7b14a2262)

**Comment by CilooW** [comment]
and then for the fact that I couldn't install the package and had to instally it manually : 
![image](https://github.com/storybookjs/addon-styling-webpack/assets/19734086/fb43aefd-991c-48e9-9c3a-1af4d949bb40)

**Comment by Integrayshaun** [comment]
@CilooW that's odd. it shouldn't be trying to install v7.1.1 of the styling-webpack addon because we're only on version 0.0.5

This tells me that your npx command is using version 7.1.1 of storybook instead of the latest which was 7.4.6 when you sent this 🤔

**Comment by jacob-granular** [comment]
I get the same issue when running the plugin expecting postcss to be configured, but nothing happens. Im on MacOS and a new install of storybook
![image](https://github.com/storybookjs/addon-styling-webpack/assets/112853801/c0970ebb-bc90-4c43-b86d-bd54d4fd2dfe)

**Comment by Integrayshaun** [comment]
@jacob-granular Can you give me more information about your storybook? Copy and paste the result of `npx storybook info` here

**Comment by marciolima-praycom** [comment]
Hey guys! I got the same issue reported by @jacob-granular .. here's the output of `npx storybook info`:

```
➜ npx storybook info                                       

Storybook Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) x64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v18.15.0/bin/yarn <----- active
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
  npmPackages:
    @storybook/react-webpack5: ^7.0.2 => 7.5.2 
```

cc: @Integrayshaun

**Comment by jacob-granular** [comment]
@Integrayshaun I've updated my comment above with the output. The only way i've managed to get storybook working with post-css is to include custom webpack config in `./storybook/main.ts`,

```async webpackFinal(config, { configType }) {
    return {
      ...config,
      module: {
        ...config.module,
        rules: [
          ...config?.module?.rules!,
          ...[
            {
              test: /\.css$/,
              use: [
                {
                  loader: 'postcss-loader',
                  options: {
                    sourceMap: true,
                  },
                },
              ],
            },
          ],
        ],
      },
    };
  },```
